.TH edoc_doclet_chunks 3 "edoc 1.2" "" "Erlang Module Definition"
.SH NAME
edoc_doclet_chunks \- Doclet generating standalone
  EEP-48  
doc chunk files.
.SH DESCRIPTION
.LP
Doclet generating standalone EEP-48 doc chunk files\&.
.LP
Section Using the EDoc API in the EDoc User\&'s Guide shows an example of using this module\&.
.SH EXPORTS
.LP
.B
run(Doclet_gen::edoc_doclet:command(), Ctxt::edoc_doclet:context()) -> ok
.br
.RS
.LP
Main doclet entry point\&.
.LP
This doclet is tightly coupled with edoc_layout_chunks and should be used together with it\&.
.LP
The only option this doclet accepts is \fIdir\fR\&, which controls where the \fIchunks\fR\& subdirectory and the EEP-48 chunk files will be placed\&.
.RE
.SH "SEE ALSO"

.LP
edoc_layout_chunks, shell_docs(3)
.SH AUTHORS
.LP
Radek Szymczyszyn
.I
<lavrin@gmail\&.com>