.TH wxActivateEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxActivateEvent \- Functions for wxActivateEvent class
.SH DESCRIPTION
.LP
An activate event is sent when a window or application is being activated or deactivated\&.
.LP
Note: Until wxWidgets 3\&.1\&.0 activation events could be sent by wxMSW when the window was minimized\&. This reflected the native MSW behaviour but was often surprising and unexpected, so starting from 3\&.1\&.0 such events are not sent any more when the window is in the minimized state\&.
.LP
See: Overview events, \fIwxApp::IsActive\fR\& (not implemented in wx)
.LP
This class is derived (and can use functions) from: \fIwxEvent\fR\&
.LP
wxWidgets docs: wxActivateEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxActivateEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxActivateEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxActivate()\fR\& = 
.br
    #wxActivate{type = wxActivateEvent:wxActivateEventType(),
.br
                active = boolean()}
.br
.fi
.nf

\fBwxActivateEventType()\fR\& = activate | activate_app | hibernate
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getActive(This) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxActivateEvent()
.br
.RE
.RE
.RS
.LP
Returns true if the application or window is being activated, false otherwise\&.
.RE