.TH wxAuiSimpleTabArt 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxAuiSimpleTabArt \- Functions for wxAuiSimpleTabArt class
.SH DESCRIPTION
.LP
Another standard tab art provider for \fIwxAuiNotebook\fR\&\&.
.LP
\fIwxAuiSimpleTabArt\fR\& is derived from \fIwxAuiTabArt\fR\& demonstrating how to write a completely new tab art class\&. It can also be used as alternative to \fIwxAuiDefaultTabArt\fR\& (not implemented in wx)\&.
.LP
This class is derived (and can use functions) from: \fIwxAuiTabArt\fR\&
.LP
wxWidgets docs: wxAuiSimpleTabArt
.SH DATA TYPES
.nf

\fBwxAuiSimpleTabArt()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxAuiSimpleTabArt()
.br
.fi
.br
.RS
.RE
.LP
.nf

.B
destroy(This :: wxAuiSimpleTabArt()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE