.TH wxBitmapDataObject 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxBitmapDataObject \- Functions for wxBitmapDataObject class
.SH DESCRIPTION
.LP
\fIwxBitmapDataObject\fR\& is a specialization of \fIwxDataObject\fR\& for bitmap data\&. It can be used without change to paste data into the \fIwxClipboard\fR\& or a \fIwxDropSource\fR\& (not implemented in wx)\&. A user may wish to derive a new class from this class for providing a bitmap on-demand in order to minimize memory consumption when offering data in several formats, such as a bitmap and GIF\&.
.LP
This class may be used as is, but \fIgetBitmap/1\fR\& may be overridden to increase efficiency\&.
.LP
See: Overview dnd, \fIwxDataObject\fR\&, \fIwxDataObjectSimple\fR\& (not implemented in wx), \fIwxFileDataObject\fR\&, \fIwxTextDataObject\fR\&, \fIwxDataObject\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxDataObject\fR\&
.LP
wxWidgets docs: wxBitmapDataObject
.SH DATA TYPES
.nf

\fBwxBitmapDataObject()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxBitmapDataObject()
.br
.fi
.br
.LP
.nf

.B
new(Options :: [Option]) -> wxBitmapDataObject()
.br
.fi
.br
.nf

.B
new(Bitmap) -> wxBitmapDataObject()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Bitmap = wxBitmap:wxBitmap()
.br
.RE
.RE
.RS
.LP
Constructor, optionally passing a bitmap (otherwise use \fIsetBitmap/2\fR\& later)\&.
.RE
.LP
.nf

.B
getBitmap(This) -> wxBitmap:wxBitmap()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxBitmapDataObject()
.br
.RE
.RE
.RS
.LP
Returns the bitmap associated with the data object\&.
.LP
You may wish to override this method when offering data on-demand, but this is not required by wxWidgets\&' internals\&. Use this method to get data in bitmap form from the \fIwxClipboard\fR\&\&.
.RE
.LP
.nf

.B
setBitmap(This, Bitmap) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxBitmapDataObject()
.br
Bitmap = wxBitmap:wxBitmap()
.br
.RE
.RE
.RS
.LP
Sets the bitmap associated with the data object\&.
.LP
This method is called when the data object receives data\&. Usually there will be no reason to override this function\&.
.RE
.LP
.nf

.B
destroy(This :: wxBitmapDataObject()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE