.TH wxCalendarEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxCalendarEvent \- Functions for wxCalendarEvent class
.SH DESCRIPTION
.LP
The \fIwxCalendarEvent\fR\& class is used together with \fIwxCalendarCtrl\fR\&\&.
.LP
See: \fIwxCalendarCtrl\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxDateEvent\fR\& \fIwxCommandEvent\fR\& \fIwxEvent\fR\&
.LP
wxWidgets docs: wxCalendarEvent
.SH DATA TYPES
.nf

\fBwxCalendarEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxCalendar()\fR\& = 
.br
    #wxCalendar{type = wxCalendarEvent:wxCalendarEventType(),
.br
                wday = wx:wx_enum(),
.br
                date = wx:wx_datetime()}
.br
.fi
.nf

\fBwxCalendarEventType()\fR\& = 
.br
    calendar_sel_changed | calendar_day_changed |
.br
    calendar_month_changed | calendar_year_changed |
.br
    calendar_doubleclicked | calendar_weekday_clicked
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getWeekDay(This) -> wx:wx_enum()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxCalendarEvent()
.br
.RE
.RE
.RS
.LP
Returns the week day on which the user clicked in \fIEVT_CALENDAR_WEEKDAY_CLICKED\fR\& handler\&.
.LP
It doesn\&'t make sense to call this function in other handlers\&.
.RE
.LP
.nf

.B
getDate(This) -> wx:wx_datetime()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxCalendarEvent()
.br
.RE
.RE
.RS
.LP
Returns the date\&.
.RE