.TH wxColourPickerCtrl 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxColourPickerCtrl \- Functions for wxColourPickerCtrl class
.SH DESCRIPTION
.LP
This control allows the user to select a colour\&. The generic implementation is a button which brings up a \fIwxColourDialog\fR\& when clicked\&. Native implementation may differ but this is usually a (small) widget which give access to the colour-chooser dialog\&. It is only available if \fIwxUSE_COLOURPICKERCTRL\fR\& is set to 1 (the default)\&.
.LP
Styles
.LP
This class supports the following styles:
.LP
See: \fIwxColourDialog\fR\&, \fIwxColourPickerEvent\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxPickerBase\fR\& \fIwxControl\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxColourPickerCtrl
.SH "EVENTS"

.LP
Event types emitted from this class: \fIcommand_colourpicker_changed\fR\&
.SH DATA TYPES
.nf

\fBwxColourPickerCtrl()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxColourPickerCtrl()
.br
.fi
.br
.RS
.RE
.LP
.nf

.B
new(Parent, Id) -> wxColourPickerCtrl()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
.RE
.RE
.LP
.nf

.B
new(Parent, Id, Options :: [Option]) -> wxColourPickerCtrl()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
Option = 
.br
    {col, wx:wx_colour()} |
.br
    {pos, {X :: integer(), Y :: integer()}} |
.br
    {size, {W :: integer(), H :: integer()}} |
.br
    {style, integer()} |
.br
    {validator, wx:wx_object()}
.br
.RE
.RE
.RS
.LP
Initializes the object and calls \fIcreate/4\fR\& with all the parameters\&.
.RE
.LP
.nf

.B
create(This, Parent, Id) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
.RE
.RE
.LP
.nf

.B
create(This, Parent, Id, Options :: [Option]) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
Parent = wxWindow:wxWindow()
.br
Id = integer()
.br
Option = 
.br
    {col, wx:wx_colour()} |
.br
    {pos, {X :: integer(), Y :: integer()}} |
.br
    {size, {W :: integer(), H :: integer()}} |
.br
    {style, integer()} |
.br
    {validator, wx:wx_object()}
.br
.RE
.RE
.RS
.LP
Creates a colour picker with the given arguments\&.
.LP
Return: true if the control was successfully created or false if creation failed\&.
.RE
.LP
.nf

.B
getColour(This) -> wx:wx_colour4()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
.RE
.RE
.RS
.LP
Returns the currently selected colour\&.
.RE
.LP
.nf

.B
setColour(This, Colname) -> ok
.br
.fi
.br
.nf

.B
setColour(This, Col) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxColourPickerCtrl()
.br
Col = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
Sets the currently selected colour\&.
.LP
See \fIwxColour::Set()\fR\& (not implemented in wx)\&.
.RE
.LP
.nf

.B
destroy(This :: wxColourPickerCtrl()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE