.TH wxDateEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxDateEvent \- Functions for wxDateEvent class
.SH DESCRIPTION
.LP
This event class holds information about a date change and is used together with \fIwxDatePickerCtrl\fR\&\&. It also serves as a base class for \fIwxCalendarEvent\fR\&\&.
.LP
This class is derived (and can use functions) from: \fIwxCommandEvent\fR\& \fIwxEvent\fR\&
.LP
wxWidgets docs: wxDateEvent
.SH DATA TYPES
.nf

\fBwxDateEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxDate()\fR\& = 
.br
    #wxDate{type = wxDateEvent:wxDateEventType(),
.br
            date = wx:wx_datetime()}
.br
.fi
.nf

\fBwxDateEventType()\fR\& = date_changed
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getDate(This) -> wx:wx_datetime()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxDateEvent()
.br
.RE
.RE
.RS
.LP
Returns the date\&.
.RE