.TH wxDCOverlay 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxDCOverlay \- Functions for wxDCOverlay class
.SH DESCRIPTION
.LP
Connects an overlay with a drawing DC\&.
.LP
See: \fIwxOverlay\fR\&, \fIwxDC\fR\& 
.LP
wxWidgets docs: wxDCOverlay
.SH DATA TYPES
.nf

\fBwxDCOverlay()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Overlay, Dc) -> wxDCOverlay()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Overlay = wxOverlay:wxOverlay()
.br
Dc = wxDC:wxDC()
.br
.RE
.RE
.RS
.LP
Convenience wrapper that behaves the same using the entire area of the dc\&.
.RE
.LP
.nf

.B
new(Overlay, Dc, X, Y, Width, Height) -> wxDCOverlay()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Overlay = wxOverlay:wxOverlay()
.br
Dc = wxDC:wxDC()
.br
X = Y = Width = Height = integer()
.br
.RE
.RE
.RS
.LP
Connects this overlay to the corresponding drawing dc, if the overlay is not initialized yet this call will do so\&.
.RE
.LP
.nf

.B
destroy(This :: wxDCOverlay()) -> ok
.br
.fi
.br
.RS
.LP
Removes the connection between the overlay and the dc\&.
.RE
.LP
.nf

.B
clear(This) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxDCOverlay()
.br
.RE
.RE
.RS
.LP
Clears the layer, restoring the state at the last init\&.
.RE