.TH wxDropFilesEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxDropFilesEvent \- Functions for wxDropFilesEvent class
.SH DESCRIPTION
.LP
This class is used for drop files events, that is, when files have been dropped onto the window\&.
.LP
The window must have previously been enabled for dropping by calling \fIwxWindow:dragAcceptFiles/2\fR\&\&.
.LP
Important note: this is a separate implementation to the more general drag and drop implementation documented in the overview_dnd\&. It uses the older, Windows message-based approach of dropping files\&.
.LP
Remark: Windows only until version 2\&.8\&.9, available on all platforms since 2\&.8\&.10\&.
.LP
See: Overview events, \fIwxWindow:dragAcceptFiles/2\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxEvent\fR\&
.LP
wxWidgets docs: wxDropFilesEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxDropFilesEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxDropFilesEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxDropFiles()\fR\& = 
.br
    #wxDropFiles{type = wxDropFilesEvent:wxDropFilesEventType(),
.br
                 pos = {X :: integer(), Y :: integer()},
.br
                 files = [unicode:chardata()]}
.br
.fi
.nf

\fBwxDropFilesEventType()\fR\& = drop_files
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getPosition(This) -> {X :: integer(), Y :: integer()}
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxDropFilesEvent()
.br
.RE
.RE
.RS
.LP
Returns the position at which the files were dropped\&.
.LP
Returns an array of filenames\&.
.RE
.LP
.nf

.B
getNumberOfFiles(This) -> integer()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxDropFilesEvent()
.br
.RE
.RE
.RS
.LP
Returns the number of files dropped\&.
.RE
.LP
.nf

.B
getFiles(This) -> [unicode:charlist()]
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxDropFilesEvent()
.br
.RE
.RE
.RS
.LP
Returns an array of filenames\&.
.RE