.TH wxFindReplaceDialog 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxFindReplaceDialog \- Functions for wxFindReplaceDialog class
.SH DESCRIPTION
.LP
\fIwxFindReplaceDialog\fR\& is a standard modeless dialog which is used to allow the user to search for some text (and possibly replace it with something else)\&.
.LP
The actual searching is supposed to be done in the owner window which is the parent of this dialog\&. Note that it means that unlike for the other standard dialogs this one \fImust\fR\& have a parent window\&. Also note that there is no way to use this dialog in a modal way; it is always, by design and implementation, modeless\&.
.LP
Please see the page_samples_dialogs sample for an example of using it\&.
.LP
This class is derived (and can use functions) from: \fIwxDialog\fR\& \fIwxTopLevelWindow\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxFindReplaceDialog
.SH DATA TYPES
.nf

\fBwxFindReplaceDialog()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxFindReplaceDialog()
.br
.fi
.br
.RS
.RE
.LP
.nf

.B
new(Parent, Data, Title) -> wxFindReplaceDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Data = wxFindReplaceData:wxFindReplaceData()
.br
Title = unicode:chardata()
.br
.RE
.RE
.LP
.nf

.B
new(Parent, Data, Title, Options :: [Option]) ->
.B
       wxFindReplaceDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Data = wxFindReplaceData:wxFindReplaceData()
.br
Title = unicode:chardata()
.br
Option = {style, integer()}
.br
.RE
.RE
.RS
.LP
After using default constructor \fIcreate/5\fR\& must be called\&.
.LP
The \fIparent\fR\& and \fIdata\fR\& parameters must be non-NULL\&.
.RE
.LP
.nf

.B
destroy(This :: wxFindReplaceDialog()) -> ok
.br
.fi
.br
.RS
.LP
Destructor\&.
.RE
.LP
.nf

.B
create(This, Parent, Data, Title) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFindReplaceDialog()
.br
Parent = wxWindow:wxWindow()
.br
Data = wxFindReplaceData:wxFindReplaceData()
.br
Title = unicode:chardata()
.br
.RE
.RE
.LP
.nf

.B
create(This, Parent, Data, Title, Options :: [Option]) ->
.B
          boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFindReplaceDialog()
.br
Parent = wxWindow:wxWindow()
.br
Data = wxFindReplaceData:wxFindReplaceData()
.br
Title = unicode:chardata()
.br
Option = {style, integer()}
.br
.RE
.RE
.RS
.LP
Creates the dialog; use \fIwxWindow:show/2\fR\& to show it on screen\&.
.LP
The \fIparent\fR\& and \fIdata\fR\& parameters must be non-NULL\&.
.RE
.LP
.nf

.B
getData(This) -> wxFindReplaceData:wxFindReplaceData()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFindReplaceDialog()
.br
.RE
.RE
.RS
.LP
Get the \fIwxFindReplaceData\fR\& object used by this dialog\&.
.RE