.TH wxFontDialog 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxFontDialog \- Functions for wxFontDialog class
.SH DESCRIPTION
.LP
This class represents the font chooser dialog\&.
.LP
See: Overview cmndlg, \fIwxFontData\fR\&, ?wxGetFontFromUser()
.LP
This class is derived (and can use functions) from: \fIwxDialog\fR\& \fIwxTopLevelWindow\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxFontDialog
.SH DATA TYPES
.nf

\fBwxFontDialog()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxFontDialog()
.br
.fi
.br
.RS
.LP
Default ctor\&.
.LP
\fIcreate/3\fR\& must be called before the dialog can be shown\&.
.RE
.LP
.nf

.B
new(Parent, Data) -> wxFontDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Data = wxFontData:wxFontData()
.br
.RE
.RE
.RS
.LP
Constructor\&.
.LP
Pass a parent window, and the \fIwxFontData\fR\& object to be used to initialize the dialog controls\&.
.RE
.LP
.nf

.B
create(This, Parent, Data) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontDialog()
.br
Parent = wxWindow:wxWindow()
.br
Data = wxFontData:wxFontData()
.br
.RE
.RE
.RS
.LP
Creates the dialog if the \fIwxFontDialog\fR\& object had been initialized using the default constructor\&.
.LP
Return: true on success and false if an error occurred\&.
.RE
.LP
.nf

.B
getFontData(This) -> wxFontData:wxFontData()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontDialog()
.br
.RE
.RE
.RS
.LP
Returns the \fIwxFontData\fR\& associated with the font dialog\&.
.RE
.LP
.nf

.B
destroy(This :: wxFontDialog()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE