.TH wxFontData 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxFontData \- Functions for wxFontData class
.SH DESCRIPTION
.LP
This class holds a variety of information related to font dialogs\&.
.LP
See: Overview cmndlg, \fIwxFont\fR\&, \fIwxFontDialog\fR\& 
.LP
wxWidgets docs: wxFontData
.SH DATA TYPES
.nf

\fBwxFontData()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxFontData()
.br
.fi
.br
.RS
.LP
Constructor\&.
.LP
Initializes \fIfontColour\fR\& to black, \fIshowHelp\fR\& to false, \fIallowSymbols\fR\& to true, \fIenableEffects\fR\& to true, \fIminSize\fR\& to 0 and \fImaxSize\fR\& to 0\&.
.RE
.LP
.nf

.B
new(Data) -> wxFontData()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Data = wxFontData()
.br
.RE
.RE
.RS
.LP
Copy Constructor\&.
.RE
.LP
.nf

.B
enableEffects(This, Enable) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
Enable = boolean()
.br
.RE
.RE
.RS
.LP
Enables or disables "effects" under Windows or generic only\&.
.LP
This refers to the controls for manipulating colour, strikeout and underline properties\&.
.LP
The default value is true\&.
.RE
.LP
.nf

.B
getAllowSymbols(This) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
.RE
.RE
.RS
.LP
Under Windows, returns a flag determining whether symbol fonts can be selected\&.
.LP
Has no effect on other platforms\&.
.LP
The default value is true\&.
.RE
.LP
.nf

.B
getColour(This) -> wx:wx_colour4()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
.RE
.RE
.RS
.LP
Gets the colour associated with the font dialog\&.
.LP
The default value is black\&.
.RE
.LP
.nf

.B
getChosenFont(This) -> wxFont:wxFont()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
.RE
.RE
.RS
.LP
Gets the font chosen by the user if the user pressed OK (\fIwxFontDialog::ShowModal()\fR\& (not implemented in wx) returned wxID_OK)\&.
.RE
.LP
.nf

.B
getEnableEffects(This) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
.RE
.RE
.RS
.LP
Determines whether "effects" are enabled under Windows\&.
.LP
This refers to the controls for manipulating colour, strikeout and underline properties\&.
.LP
The default value is true\&.
.RE
.LP
.nf

.B
getInitialFont(This) -> wxFont:wxFont()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
.RE
.RE
.RS
.LP
Gets the font that will be initially used by the font dialog\&.
.LP
This should have previously been set by the application\&.
.RE
.LP
.nf

.B
getShowHelp(This) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
.RE
.RE
.RS
.LP
Returns true if the Help button will be shown (Windows only)\&.
.LP
The default value is false\&.
.RE
.LP
.nf

.B
setAllowSymbols(This, AllowSymbols) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
AllowSymbols = boolean()
.br
.RE
.RE
.RS
.LP
Under Windows, determines whether symbol fonts can be selected\&.
.LP
Has no effect on other platforms\&.
.LP
The default value is true\&.
.RE
.LP
.nf

.B
setChosenFont(This, Font) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
Font = wxFont:wxFont()
.br
.RE
.RE
.RS
.LP
Sets the font that will be returned to the user (for internal use only)\&.
.RE
.LP
.nf

.B
setColour(This, Colour) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
Colour = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
Sets the colour that will be used for the font foreground colour\&.
.LP
The default colour is black\&.
.RE
.LP
.nf

.B
setInitialFont(This, Font) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
Font = wxFont:wxFont()
.br
.RE
.RE
.RS
.LP
Sets the font that will be initially used by the font dialog\&.
.RE
.LP
.nf

.B
setRange(This, Min, Max) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
Min = Max = integer()
.br
.RE
.RE
.RS
.LP
Sets the valid range for the font point size (Windows only)\&.
.LP
The default is 0, 0 (unrestricted range)\&.
.RE
.LP
.nf

.B
setShowHelp(This, ShowHelp) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxFontData()
.br
ShowHelp = boolean()
.br
.RE
.RE
.RS
.LP
Determines whether the Help button will be displayed in the font dialog (Windows only)\&.
.LP
The default value is false\&.
.RE
.LP
.nf

.B
destroy(This :: wxFontData()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE