.TH wxGridCellFloatEditor 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGridCellFloatEditor \- Functions for wxGridCellFloatEditor class
.SH DESCRIPTION
.LP
The editor for floating point numbers data\&.
.LP
See: \fIwxGridCellEditor\fR\&, \fIwxGridCellAutoWrapStringEditor\fR\& (not implemented in wx), \fIwxGridCellBoolEditor\fR\&, \fIwxGridCellChoiceEditor\fR\&, \fIwxGridCellEnumEditor\fR\& (not implemented in wx), \fIwxGridCellNumberEditor\fR\&, \fIwxGridCellTextEditor\fR\&, \fIwxGridCellDateEditor\fR\& (not implemented in wx)
.LP
This class is derived (and can use functions) from: \fIwxGridCellEditor\fR\&
.LP
wxWidgets docs: wxGridCellFloatEditor
.SH DATA TYPES
.nf

\fBwxGridCellFloatEditor()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxGridCellFloatEditor()
.br
.fi
.br
.LP
.nf

.B
new(Options :: [Option]) -> wxGridCellFloatEditor()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Option = 
.br
    {width, integer()} |
.br
    {precision, integer()} |
.br
    {format, integer()}
.br
.RE
.RE
.RS
.LP
Float cell editor ctor\&.
.RE
.LP
.nf

.B
setParameters(This, Params) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGridCellFloatEditor()
.br
Params = unicode:chardata()
.br
.RE
.RE
.RS
.LP
The parameters string format is "width[,precision[,format]]" where \fIformat\fR\& should be chosen between f|e|g|E|G (f is used by default)
.RE
.LP
.nf

.B
destroy(This :: wxGridCellFloatEditor()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE