.TH wxGridCellNumberEditor 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGridCellNumberEditor \- Functions for wxGridCellNumberEditor class
.SH DESCRIPTION
.LP
Grid cell editor for numeric integer data\&.
.LP
See: \fIwxGridCellEditor\fR\&, \fIwxGridCellAutoWrapStringEditor\fR\& (not implemented in wx), \fIwxGridCellBoolEditor\fR\&, \fIwxGridCellChoiceEditor\fR\&, \fIwxGridCellEnumEditor\fR\& (not implemented in wx), \fIwxGridCellFloatEditor\fR\&, \fIwxGridCellTextEditor\fR\&, \fIwxGridCellDateEditor\fR\& (not implemented in wx)
.LP
This class is derived (and can use functions) from: \fIwxGridCellTextEditor\fR\& \fIwxGridCellEditor\fR\&
.LP
wxWidgets docs: wxGridCellNumberEditor
.SH DATA TYPES
.nf

\fBwxGridCellNumberEditor()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxGridCellNumberEditor()
.br
.fi
.br
.LP
.nf

.B
new(Options :: [Option]) -> wxGridCellNumberEditor()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Option = {min, integer()} | {max, integer()}
.br
.RE
.RE
.RS
.LP
Allows you to specify the range for acceptable data\&.
.LP
Values equal to -1 for both \fImin\fR\& and \fImax\fR\& indicate that no range checking should be done\&.
.RE
.LP
.nf

.B
getValue(This) -> unicode:charlist()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGridCellNumberEditor()
.br
.RE
.RE
.RS
.LP
Returns the value currently in the editor control\&.
.RE
.LP
.nf

.B
setParameters(This, Params) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGridCellNumberEditor()
.br
Params = unicode:chardata()
.br
.RE
.RE
.RS
.LP
Parameters string format is "min,max"\&.
.RE
.LP
.nf

.B
destroy(This :: wxGridCellNumberEditor()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE