.TH wxGraphicsObject 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGraphicsObject \- Functions for wxGraphicsObject class
.SH DESCRIPTION
.LP
This class is the superclass of native graphics objects like pens etc\&. It allows reference counting\&. Not instantiated by user code\&.
.LP
See: \fIwxGraphicsBrush\fR\&, \fIwxGraphicsPen\fR\&, \fIwxGraphicsMatrix\fR\&, \fIwxGraphicsPath\fR\& 
.LP
wxWidgets docs: wxGraphicsObject
.SH DATA TYPES
.nf

\fBwxGraphicsObject()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
destroy(This :: wxGraphicsObject()) -> ok
.br
.fi
.br
.RS
.RE
.LP
.nf

.B
getRenderer(This) -> wxGraphicsRenderer:wxGraphicsRenderer()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsObject()
.br
.RE
.RE
.RS
.LP
Returns the renderer that was used to create this instance, or NULL if it has not been initialized yet\&.
.RE
.LP
.nf

.B
isNull(This) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsObject()
.br
.RE
.RE
.RS
.LP
Return: false if this object is valid, otherwise returns true\&.
.RE