.TH wxGridCellBoolRenderer 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGridCellBoolRenderer \- Functions for wxGridCellBoolRenderer class
.SH DESCRIPTION
.LP
This class may be used to format boolean data in a cell\&.
.LP
See: \fIwxGridCellRenderer\fR\&, \fIwxGridCellAutoWrapStringRenderer\fR\& (not implemented in wx), \fIwxGridCellDateTimeRenderer\fR\& (not implemented in wx), \fIwxGridCellEnumRenderer\fR\& (not implemented in wx), \fIwxGridCellFloatRenderer\fR\&, \fIwxGridCellNumberRenderer\fR\&, \fIwxGridCellStringRenderer\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxGridCellRenderer\fR\&
.LP
wxWidgets docs: wxGridCellBoolRenderer
.SH DATA TYPES
.nf

\fBwxGridCellBoolRenderer()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxGridCellBoolRenderer()
.br
.fi
.br
.RS
.RE
.LP
.nf

.B
destroy(This :: wxGridCellBoolRenderer()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE