.TH wxGridCellStringRenderer 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGridCellStringRenderer \- Functions for wxGridCellStringRenderer class
.SH DESCRIPTION
.LP
This class may be used to format string data in a cell; it is the default for string cells\&.
.LP
See: \fIwxGridCellRenderer\fR\&, \fIwxGridCellAutoWrapStringRenderer\fR\& (not implemented in wx), \fIwxGridCellBoolRenderer\fR\&, \fIwxGridCellDateTimeRenderer\fR\& (not implemented in wx), \fIwxGridCellEnumRenderer\fR\& (not implemented in wx), \fIwxGridCellFloatRenderer\fR\&, \fIwxGridCellNumberRenderer\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxGridCellRenderer\fR\&
.LP
wxWidgets docs: wxGridCellStringRenderer
.SH DATA TYPES
.nf

\fBwxGridCellStringRenderer()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxGridCellStringRenderer()
.br
.fi
.br
.RS
.RE
.LP
.nf

.B
destroy(This :: wxGridCellStringRenderer()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE