.TH wxGraphicsGradientStops 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGraphicsGradientStops \- Represents a collection of wxGraphicGradientStop values for use with CreateLinearGradientBrush and CreateRadialGradientBrush. 
.SH DESCRIPTION
.LP
The stops are maintained in order of position\&. If two or more stops are added with the same position then the one(s) added later come later\&. This can be useful for producing discontinuities in the colour gradient\&.
.LP
Notice that this class is write-once, you can\&'t modify the stops once they had been added\&.
.LP
Since: 2\&.9\&.1
.LP
wxWidgets docs: wxGraphicsGradientStops
.SH DATA TYPES
.nf

\fBwxGraphicsGradientStops()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxGraphicsGradientStops()
.br
.fi
.br
.LP
.nf

.B
new(Options :: [Option]) -> wxGraphicsGradientStops()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Option = {startCol, wx:wx_colour()} | {endCol, wx:wx_colour()}
.br
.RE
.RE
.RS
.LP
Initializes the gradient stops with the given boundary colours\&.
.LP
Creates a \fIwxGraphicsGradientStops\fR\& instance with start colour given by \fIstartCol\fR\& and end colour given by \fIendCol\fR\&\&.
.RE
.LP
.nf

.B
item(This, N) -> {wx:wx_colour4(), float()}
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
N = integer()
.br
.RE
.RE
.RS
.LP
Returns the stop at the given index\&.
.RE
.LP
.nf

.B
getCount(This) -> integer()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
.RE
.RE
.RS
.LP
Returns the number of stops\&.
.RE
.LP
.nf

.B
setStartColour(This, Col) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
Col = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
Set the start colour to \fIcol\fR\&\&.
.RE
.LP
.nf

.B
getStartColour(This) -> wx:wx_colour4()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
.RE
.RE
.RS
.LP
Returns the start colour\&.
.RE
.LP
.nf

.B
setEndColour(This, Col) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
Col = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
Set the end colour to \fIcol\fR\&\&.
.RE
.LP
.nf

.B
getEndColour(This) -> wx:wx_colour4()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
.RE
.RE
.RS
.LP
Returns the end colour\&.
.RE
.LP
.nf

.B
add(This, Col, Pos) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxGraphicsGradientStops()
.br
Col = wx:wx_colour()
.br
Pos = number()
.br
.RE
.RE
.RS
.LP
Add a new stop\&.
.RE
.LP
.nf

.B
destroy(This :: wxGraphicsGradientStops()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE