.TH wxGridCellNumberRenderer 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxGridCellNumberRenderer \- Functions for wxGridCellNumberRenderer class
.SH DESCRIPTION
.LP
This class may be used to format integer data in a cell\&.
.LP
See: \fIwxGridCellRenderer\fR\&, \fIwxGridCellAutoWrapStringRenderer\fR\& (not implemented in wx), \fIwxGridCellBoolRenderer\fR\&, \fIwxGridCellDateTimeRenderer\fR\& (not implemented in wx), \fIwxGridCellEnumRenderer\fR\& (not implemented in wx), \fIwxGridCellFloatRenderer\fR\&, \fIwxGridCellStringRenderer\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxGridCellStringRenderer\fR\& \fIwxGridCellRenderer\fR\&
.LP
wxWidgets docs: wxGridCellNumberRenderer
.SH DATA TYPES
.nf

\fBwxGridCellNumberRenderer()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxGridCellNumberRenderer()
.br
.fi
.br
.RS
.LP
Default constructor\&.
.RE
.LP
.nf

.B
destroy(This :: wxGridCellNumberRenderer()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE