.TH wxMask 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMask \- Functions for wxMask class
.SH DESCRIPTION
.LP
This class encapsulates a monochrome mask bitmap, where the masked area is black and the unmasked area is white\&.
.LP
When associated with a bitmap and drawn in a device context, the unmasked area of the bitmap will be drawn, and the masked area will not be drawn\&.
.LP
Note: A mask can be associated also with a bitmap with an alpha channel but drawing such bitmaps under wxMSW may be slow so using them should be avoided if drawing performance is an important factor\&.
.LP
See: \fIwxBitmap\fR\&, \fIwxDC:blit/6\fR\&, \fIwxMemoryDC\fR\& 
.LP
wxWidgets docs: wxMask
.SH DATA TYPES
.nf

\fBwxMask()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxMask()
.br
.fi
.br
.RS
.LP
Default constructor\&.
.RE
.LP
.nf

.B
new(Bitmap) -> wxMask()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Bitmap = wxBitmap:wxBitmap()
.br
.RE
.RE
.RS
.LP
Constructs a mask from a monochrome bitmap\&.
.RE
.LP
.nf

.B
new(Bitmap, Index) -> wxMask()
.br
.fi
.br
.nf

.B
new(Bitmap, Colour) -> wxMask()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Bitmap = wxBitmap:wxBitmap()
.br
Colour = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
Constructs a mask from a bitmap and a colour that indicates the background\&.
.RE
.LP
.nf

.B
destroy(This :: wxMask()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the \fIwxMask\fR\& object and the underlying bitmap data\&.
.RE
.LP
.nf

.B
create(This, Bitmap) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMask()
.br
Bitmap = wxBitmap:wxBitmap()
.br
.RE
.RE
.RS
.LP
Constructs a mask from a monochrome bitmap\&.
.RE
.LP
.nf

.B
create(This, Bitmap, Index) -> boolean()
.br
.fi
.br
.nf

.B
create(This, Bitmap, Colour) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMask()
.br
Bitmap = wxBitmap:wxBitmap()
.br
Colour = wx:wx_colour()
.br
.RE
.RE
.RS
.LP
Constructs a mask from a bitmap and a colour that indicates the background\&.
.RE