.TH wxMDIClientWindow 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMDIClientWindow \- Functions for wxMDIClientWindow class
.SH DESCRIPTION
.LP
An MDI client window is a child of \fIwxMDIParentFrame\fR\&, and manages zero or more \fIwxMDIChildFrame\fR\& objects\&.
.LP
The client window is the area where MDI child windows exist\&. It doesn\&'t have to cover the whole parent frame; other windows such as toolbars and a help window might coexist with it\&. There can be scrollbars on a client window, which are controlled by the parent window style\&.
.LP
The \fIwxMDIClientWindow\fR\& class is usually adequate without further derivation, and it is created automatically when the MDI parent frame is created\&. If the application needs to derive a new class, the function \fIwxMDIParentFrame::OnCreateClient()\fR\& (not implemented in wx) must be overridden in order to give an opportunity to use a different class of client window\&.
.LP
Under wxMSW, the client window will automatically have a sunken border style when the active child is not maximized, and no border style when a child is maximized\&.
.LP
See: \fIwxMDIChildFrame\fR\&, \fIwxMDIParentFrame\fR\&, \fIwxFrame\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxMDIClientWindow
.SH DATA TYPES
.nf

\fBwxMDIClientWindow()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxMDIClientWindow()
.br
.fi
.br
.RS
.LP
Default constructor\&.
.LP
Objects of this class are only created by \fIwxMDIParentFrame\fR\& which uses the default constructor and calls \fIcreateClient/3\fR\& immediately afterwards\&.
.RE
.LP
.nf

.B
createClient(This, Parent) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMDIClientWindow()
.br
Parent = wxMDIParentFrame:wxMDIParentFrame()
.br
.RE
.RE
.LP
.nf

.B
createClient(This, Parent, Options :: [Option]) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMDIClientWindow()
.br
Parent = wxMDIParentFrame:wxMDIParentFrame()
.br
Option = {style, integer()}
.br
.RE
.RE
.RS
.LP
Called by \fIwxMDIParentFrame\fR\& immediately after creating the client window\&.
.LP
This function may be overridden in the derived class but the base class version must usually be called first to really create the window\&.
.RE
.LP
.nf

.B
destroy(This :: wxMDIClientWindow()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE