.TH wxMirrorDC 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMirrorDC \- Functions for wxMirrorDC class
.SH DESCRIPTION
.LP
\fIwxMirrorDC\fR\& is a simple wrapper class which is always associated with a real \fIwxDC\fR\& object and either forwards all of its operations to it without changes (no mirroring takes place) or exchanges \fIx\fR\& and \fIy\fR\& coordinates which makes it possible to reuse the same code to draw a figure and its mirror - i\&.e\&. reflection related to the diagonal line x == y\&.
.LP
Since: 2\&.5\&.0
.LP
This class is derived (and can use functions) from: \fIwxDC\fR\&
.LP
wxWidgets docs: wxMirrorDC
.SH DATA TYPES
.nf

\fBwxMirrorDC()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Dc, Mirror) -> wxMirrorDC()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Dc = wxDC:wxDC()
.br
Mirror = boolean()
.br
.RE
.RE
.RS
.LP
Creates a (maybe) mirrored DC associated with the real \fIdc\fR\&\&.
.LP
Everything drawn on \fIwxMirrorDC\fR\& will appear (and maybe mirrored) on \fIdc\fR\&\&.
.LP
\fImirror\fR\& specifies if we do mirror (if it is true) or not (if it is false)\&.
.RE
.LP
.nf

.B
destroy(This :: wxMirrorDC()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE