.TH wxMoveEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMoveEvent \- Functions for wxMoveEvent class
.SH DESCRIPTION
.LP
A move event holds information about window position change\&.
.LP
These events are currently generated for top level (see \fIwxTopLevelWindow\fR\&) windows in all ports, but are not generated for the child windows in wxGTK\&.
.LP
See: {X,Y}, Overview events 
.LP
This class is derived (and can use functions) from: \fIwxEvent\fR\&
.LP
wxWidgets docs: wxMoveEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxMoveEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxMoveEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxMove()\fR\& = 
.br
    #wxMove{type = wxMoveEvent:wxMoveEventType(),
.br
            pos = {X :: integer(), Y :: integer()},
.br
            rect =
.br
                {X :: integer(),
.br
                 Y :: integer(),
.br
                 W :: integer(),
.br
                 H :: integer()}}
.br
.fi
.nf

\fBwxMoveEventType()\fR\& = move
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getPosition(This) -> {X :: integer(), Y :: integer()}
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMoveEvent()
.br
.RE
.RE
.RS
.LP
Returns the position of the window generating the move change event\&.
.RE
.LP
.nf

.B
getRect(This) ->
.B
           {X :: integer(),
.B
            Y :: integer(),
.B
            W :: integer(),
.B
            H :: integer()}
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMoveEvent()
.br
.RE
.RE
.RS
.RE