.TH wxMouseCaptureChangedEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMouseCaptureChangedEvent \- Functions for wxMouseCaptureChangedEvent class
.SH DESCRIPTION
.LP
An mouse capture changed event is sent to a window that loses its mouse capture\&. This is called even if \fIwxWindow:releaseMouse/1\fR\& was called by the application code\&. Handling this event allows an application to cater for unexpected capture releases which might otherwise confuse mouse handling code\&.
.LP
Only for:wxmsw
.LP
See: \fIwxMouseCaptureLostEvent\fR\&, Overview events, \fIwxWindow:captureMouse/1\fR\&, \fIwxWindow:releaseMouse/1\fR\&, \fIwxWindow:getCapture/0\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxEvent\fR\&
.LP
wxWidgets docs: wxMouseCaptureChangedEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxMouseCaptureChangedEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxMouseCaptureChangedEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxMouseCaptureChanged()\fR\& = 
.br
    #wxMouseCaptureChanged{type =
.br
                               wxMouseCaptureChangedEvent:wxMouseCaptureChangedEventType()}
.br
.fi
.nf

\fBwxMouseCaptureChangedEventType()\fR\& = mouse_capture_changed
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getCapturedWindow(This) -> wxWindow:wxWindow()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMouseCaptureChangedEvent()
.br
.RE
.RE
.RS
.LP
Returns the window that gained the capture, or NULL if it was a non-wxWidgets window\&.
.RE