.TH wxMouseCaptureLostEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMouseCaptureLostEvent \- Functions for wxMouseCaptureLostEvent class
.SH DESCRIPTION
.LP
A mouse capture lost event is sent to a window that had obtained mouse capture, which was subsequently lost due to an "external" event (for example, when a dialog box is shown or if another application captures the mouse)\&.
.LP
If this happens, this event is sent to all windows that are on the capture stack (i\&.e\&. called CaptureMouse, but didn\&'t call ReleaseMouse yet)\&. The event is not sent if the capture changes because of a call to CaptureMouse or ReleaseMouse\&.
.LP
This event is currently emitted under Windows only\&.
.LP
Only for:wxmsw
.LP
See: \fIwxMouseCaptureChangedEvent\fR\&, Overview events, \fIwxWindow:captureMouse/1\fR\&, \fIwxWindow:releaseMouse/1\fR\&, \fIwxWindow:getCapture/0\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxEvent\fR\&
.LP
wxWidgets docs: wxMouseCaptureLostEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxMouseCaptureLostEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxMouseCaptureLostEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxMouseCaptureLost()\fR\& = 
.br
    #wxMouseCaptureLost{type =
.br
                            wxMouseCaptureLostEvent:wxMouseCaptureLostEventType()}
.br
.fi
.nf

\fBwxMouseCaptureLostEventType()\fR\& = mouse_capture_lost
.br
.fi