.TH wxMultiChoiceDialog 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxMultiChoiceDialog \- Functions for wxMultiChoiceDialog class
.SH DESCRIPTION
.LP
This class represents a dialog that shows a list of strings, and allows the user to select one or more\&.
.LP
Styles
.LP
This class supports the following styles:
.LP
See: Overview cmndlg, \fIwxSingleChoiceDialog\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxDialog\fR\& \fIwxTopLevelWindow\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxMultiChoiceDialog
.SH DATA TYPES
.nf

\fBwxMultiChoiceDialog()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Parent, Message, Caption, Choices) -> wxMultiChoiceDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Message = Caption = unicode:chardata()
.br
Choices = [unicode:chardata()]
.br
.RE
.RE
.LP
.nf

.B
new(Parent, Message, Caption, Choices, Options :: [Option]) ->
.B
       wxMultiChoiceDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Message = Caption = unicode:chardata()
.br
Choices = [unicode:chardata()]
.br
Option = 
.br
    {style, integer()} | {pos, {X :: integer(), Y :: integer()}}
.br
.RE
.RE
.RS
.LP
Constructor taking an array of \fIwxString\fR\& (not implemented in wx) choices\&.
.LP
Remark: Use \fIwxDialog:showModal/1\fR\& to show the dialog\&.
.RE
.LP
.nf

.B
getSelections(This) -> [integer()]
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMultiChoiceDialog()
.br
.RE
.RE
.RS
.LP
Returns array with indexes of selected items\&.
.RE
.LP
.nf

.B
setSelections(This, Selections) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxMultiChoiceDialog()
.br
Selections = [integer()]
.br
.RE
.RE
.RS
.LP
Sets selected items from the array of selected items\&' indexes\&.
.RE
.LP
.nf

.B
destroy(This :: wxMultiChoiceDialog()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE