.TH wxPasswordEntryDialog 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxPasswordEntryDialog \- Functions for wxPasswordEntryDialog class
.SH DESCRIPTION
.LP
This class represents a dialog that requests a one-line password string from the user\&.
.LP
It is implemented as a generic wxWidgets dialog\&.
.LP
See: Overview cmndlg 
.LP
This class is derived (and can use functions) from: \fIwxTextEntryDialog\fR\& \fIwxDialog\fR\& \fIwxTopLevelWindow\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxPasswordEntryDialog
.SH DATA TYPES
.nf

\fBwxPasswordEntryDialog()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Parent, Message) -> wxPasswordEntryDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Message = unicode:chardata()
.br
.RE
.RE
.LP
.nf

.B
new(Parent, Message, Options :: [Option]) ->
.B
       wxPasswordEntryDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Message = unicode:chardata()
.br
Option = 
.br
    {caption, unicode:chardata()} |
.br
    {value, unicode:chardata()} |
.br
    {style, integer()} |
.br
    {pos, {X :: integer(), Y :: integer()}}
.br
.RE
.RE
.RS
.LP
Constructor\&.
.LP
Use \fIwxDialog:showModal/1\fR\& to show the dialog\&.
.RE
.LP
.nf

.B
destroy(This :: wxPasswordEntryDialog()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE