.TH wxPaintDC 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxPaintDC \- Functions for wxPaintDC class
.SH DESCRIPTION
.LP
A \fIwxPaintDC\fR\& must be constructed if an application wishes to paint on the client area of a window from within an EVT_PAINT() event handler\&. This should normally be constructed as a temporary stack object; don\&'t store a \fIwxPaintDC\fR\& object\&. If you have an EVT_PAINT() handler, you \fImust\fR\& create a \fIwxPaintDC\fR\& object within it even if you don\&'t actually use it\&.
.LP
Using \fIwxPaintDC\fR\& within your EVT_PAINT() handler is important because it automatically sets the clipping area to the damaged area of the window\&. Attempts to draw outside this area do not appear\&.
.LP
A \fIwxPaintDC\fR\& object is initialized to use the same font and colours as the window it is associated with\&.
.LP
See: \fIwxDC\fR\&, \fIwxClientDC\fR\&, \fIwxMemoryDC\fR\&, \fIwxWindowDC\fR\&, \fIwxScreenDC\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxWindowDC\fR\& \fIwxDC\fR\&
.LP
wxWidgets docs: wxPaintDC
.SH DATA TYPES
.nf

\fBwxPaintDC()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Window) -> wxPaintDC()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Window = wxWindow:wxWindow()
.br
.RE
.RE
.RS
.LP
Constructor\&.
.LP
Pass a pointer to the window on which you wish to paint\&.
.RE
.LP
.nf

.B
destroy(This :: wxPaintDC()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE