.TH wxPopupTransientWindow 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxPopupTransientWindow \- Functions for wxPopupTransientWindow class
.SH DESCRIPTION
.LP
A \fIwxPopupWindow\fR\& which disappears automatically when the user clicks mouse outside it or if it loses focus in any other way\&.
.LP
This window can be useful for implementing custom combobox-like controls for example\&.
.LP
See: \fIwxPopupWindow\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxPopupWindow\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxPopupTransientWindow
.SH DATA TYPES
.nf

\fBwxPopupTransientWindow()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxPopupTransientWindow()
.br
.fi
.br
.RS
.LP
Default constructor\&.
.RE
.LP
.nf

.B
new(Parent) -> wxPopupTransientWindow()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
.RE
.RE
.LP
.nf

.B
new(Parent, Options :: [Option]) -> wxPopupTransientWindow()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Option = {style, integer()}
.br
.RE
.RE
.RS
.LP
Constructor\&.
.RE
.LP
.nf

.B
popup(This) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxPopupTransientWindow()
.br
.RE
.RE
.LP
.nf

.B
popup(This, Options :: [Option]) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxPopupTransientWindow()
.br
Option = {focus, wxWindow:wxWindow()}
.br
.RE
.RE
.RS
.LP
Popup the window (this will show it too)\&.
.LP
If \fIfocus\fR\& is non-NULL, it will be kept focused while this window is shown if supported by the current platform, otherwise the popup itself will receive focus\&. In any case, the popup will disappear automatically if it loses focus because of a user action\&.
.LP
See: \fIdismiss/1\fR\& 
.RE
.LP
.nf

.B
dismiss(This) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxPopupTransientWindow()
.br
.RE
.RE
.RS
.LP
Hide the window\&.
.RE
.LP
.nf

.B
destroy(This :: wxPopupTransientWindow()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE