.TH wxPreviewCanvas 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxPreviewCanvas \- Functions for wxPreviewCanvas class
.SH DESCRIPTION
.LP
A preview canvas is the default canvas used by the print preview system to display the preview\&.
.LP
See: \fIwxPreviewFrame\fR\&, \fIwxPreviewControlBar\fR\&, \fIwxPrintPreview\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxScrolledWindow\fR\& \fIwxPanel\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxPreviewCanvas
.SH DATA TYPES
.nf

\fBwxPreviewCanvas()\fR\& = wx:wx_object()
.br
.fi