.TH wxPrintDialog 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxPrintDialog \- Functions for wxPrintDialog class
.SH DESCRIPTION
.LP
This class represents the print and print setup common dialogs\&. You may obtain a \fIwxPrinterDC\fR\& (not implemented in wx) device context from a successfully dismissed print dialog\&.
.LP
See: Overview printing, Overview cmndlg 
.LP
This class is derived (and can use functions) from: \fIwxDialog\fR\& \fIwxTopLevelWindow\fR\& \fIwxWindow\fR\& \fIwxEvtHandler\fR\&
.LP
wxWidgets docs: wxPrintDialog
.SH DATA TYPES
.nf

\fBwxPrintDialog()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Parent) -> wxPrintDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
.RE
.RE
.LP
.nf

.B
new(Parent, Options :: [Option]) -> wxPrintDialog()
.br
.fi
.br
.nf

.B
new(Parent, Data) -> wxPrintDialog()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Parent = wxWindow:wxWindow()
.br
Data = wxPrintData:wxPrintData()
.br
.RE
.RE
.RS
.RE
.LP
.nf

.B
destroy(This :: wxPrintDialog()) -> ok
.br
.fi
.br
.RS
.LP
Destructor\&.
.LP
If \fIgetPrintDC/1\fR\& has not been called, the device context obtained by the dialog (if any) will be deleted\&.
.RE
.LP
.nf

.B
getPrintDialogData(This) -> wxPrintDialogData:wxPrintDialogData()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxPrintDialog()
.br
.RE
.RE
.RS
.LP
Returns the print dialog data associated with the print dialog\&.
.RE
.LP
.nf

.B
getPrintDC(This) -> wxDC:wxDC()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxPrintDialog()
.br
.RE
.RE
.RS
.LP
Returns the device context created by the print dialog, if any\&.
.LP
When this function has been called, the ownership of the device context is transferred to the application, so it must then be deleted explicitly\&.
.RE