.TH wxQueryNewPaletteEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxQueryNewPaletteEvent \- Functions for wxQueryNewPaletteEvent class
.SH DESCRIPTION
.LP
This class is derived (and can use functions) from: \fIwxEvent\fR\&
.LP
wxWidgets docs: wxQueryNewPaletteEvent
.SH DATA TYPES
.nf

\fBwxQueryNewPaletteEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxQueryNewPalette()\fR\& = 
.br
    #wxQueryNewPalette{type =
.br
                           wxQueryNewPaletteEvent:wxQueryNewPaletteEventType()}
.br
.fi
.nf

\fBwxQueryNewPaletteEventType()\fR\& = query_new_palette
.br
.fi
.SH EXPORTS
.LP
.nf

.B
setPaletteRealized(This, Realized) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxQueryNewPaletteEvent()
.br
Realized = boolean()
.br
.RE
.RE
.RS
.RE
.LP
.nf

.B
getPaletteRealized(This) -> boolean()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxQueryNewPaletteEvent()
.br
.RE
.RE
.RS
.RE