.TH wxScreenDC 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxScreenDC \- Functions for wxScreenDC class
.SH DESCRIPTION
.LP
A \fIwxScreenDC\fR\& can be used to paint on the screen\&. This should normally be constructed as a temporary stack object; don\&'t store a \fIwxScreenDC\fR\& object\&.
.LP
When using multiple monitors, \fIwxScreenDC\fR\& corresponds to the entire virtual screen composed of all of them\&. Notice that coordinates on \fIwxScreenDC\fR\& can be negative in this case, see \fIwxDisplay:getGeometry/1\fR\& for more\&.
.LP
See: \fIwxDC\fR\&, \fIwxMemoryDC\fR\&, \fIwxPaintDC\fR\&, \fIwxClientDC\fR\&, \fIwxWindowDC\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxDC\fR\&
.LP
wxWidgets docs: wxScreenDC
.SH DATA TYPES
.nf

\fBwxScreenDC()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxScreenDC()
.br
.fi
.br
.RS
.LP
Constructor\&.
.RE
.LP
.nf

.B
destroy(This :: wxScreenDC()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE