.TH wxStdDialogButtonSizer 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxStdDialogButtonSizer \- Functions for wxStdDialogButtonSizer class
.SH DESCRIPTION
.LP
This class creates button layouts which conform to the standard button spacing and ordering defined by the platform or toolkit\&'s user interface guidelines (if such things exist)\&. By using this class, you can ensure that all your standard dialogs look correct on all major platforms\&. Currently it conforms to the Windows, GTK+ and macOS human interface guidelines\&.
.LP
When there aren\&'t interface guidelines defined for a particular platform or toolkit, \fIwxStdDialogButtonSizer\fR\& reverts to the Windows implementation\&.
.LP
To use this class, first add buttons to the sizer by calling \fIaddButton/2\fR\& (or \fIsetAffirmativeButton/2\fR\&, \fIsetNegativeButton/2\fR\& or \fIsetCancelButton/2\fR\&) and then call Realize in order to create the actual button layout used\&. Other than these special operations, this sizer works like any other sizer\&.
.LP
If you add a button with wxID_SAVE, on macOS the button will be renamed to "Save" and the wxID_NO button will be renamed to "Don\&'t Save" in accordance with the macOS Human Interface Guidelines\&.
.LP
See: \fIwxSizer\fR\&, Overview sizer, \fIwxDialog:createButtonSizer/2\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxBoxSizer\fR\& \fIwxSizer\fR\&
.LP
wxWidgets docs: wxStdDialogButtonSizer
.SH DATA TYPES
.nf

\fBwxStdDialogButtonSizer()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new() -> wxStdDialogButtonSizer()
.br
.fi
.br
.RS
.LP
Constructor for a \fIwxStdDialogButtonSizer\fR\&\&.
.RE
.LP
.nf

.B
addButton(This, Button) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxStdDialogButtonSizer()
.br
Button = wxButton:wxButton()
.br
.RE
.RE
.RS
.LP
Adds a button to the \fIwxStdDialogButtonSizer\fR\&\&.
.LP
The \fIbutton\fR\& must have one of the following identifiers:
.RE
.LP
.nf

.B
realize(This) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxStdDialogButtonSizer()
.br
.RE
.RE
.RS
.LP
Rearranges the buttons and applies proper spacing between buttons to make them match the platform or toolkit\&'s interface guidelines\&.
.RE
.LP
.nf

.B
setAffirmativeButton(This, Button) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxStdDialogButtonSizer()
.br
Button = wxButton:wxButton()
.br
.RE
.RE
.RS
.LP
Sets the affirmative button for the sizer\&.
.LP
This allows you to use identifiers other than the standard identifiers outlined above\&.
.RE
.LP
.nf

.B
setCancelButton(This, Button) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxStdDialogButtonSizer()
.br
Button = wxButton:wxButton()
.br
.RE
.RE
.RS
.LP
Sets the cancel button for the sizer\&.
.LP
This allows you to use identifiers other than the standard identifiers outlined above\&.
.RE
.LP
.nf

.B
setNegativeButton(This, Button) -> ok
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxStdDialogButtonSizer()
.br
Button = wxButton:wxButton()
.br
.RE
.RE
.RS
.LP
Sets the negative button for the sizer\&.
.LP
This allows you to use identifiers other than the standard identifiers outlined above\&.
.RE
.LP
.nf

.B
destroy(This :: wxStdDialogButtonSizer()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE