.TH wxStaticBoxSizer 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxStaticBoxSizer \- Functions for wxStaticBoxSizer class
.SH DESCRIPTION
.LP
\fIwxStaticBoxSizer\fR\& is a sizer derived from \fIwxBoxSizer\fR\& but adds a static box around the sizer\&.
.LP
The static box may be either created independently or the sizer may create it itself as a convenience\&. In any case, the sizer owns the \fIwxStaticBox\fR\& control and will delete it in the \fIwxStaticBoxSizer\fR\& destructor\&.
.LP
Note that since wxWidgets 2\&.9\&.1 you are encouraged to create the windows which are added to \fIwxStaticBoxSizer\fR\& as children of \fIwxStaticBox\fR\& itself, see this class documentation for more details\&.
.LP
Example of use of this class:
.LP
See: \fIwxSizer\fR\&, \fIwxStaticBox\fR\&, \fIwxBoxSizer\fR\&, Overview sizer 
.LP
This class is derived (and can use functions) from: \fIwxBoxSizer\fR\& \fIwxSizer\fR\&
.LP
wxWidgets docs: wxStaticBoxSizer
.SH DATA TYPES
.nf

\fBwxStaticBoxSizer()\fR\& = wx:wx_object()
.br
.fi
.SH EXPORTS
.LP
.nf

.B
new(Orient, Parent) -> wxStaticBoxSizer()
.br
.fi
.br
.nf

.B
new(Box, Orient) -> wxStaticBoxSizer()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Box = wxStaticBox:wxStaticBox()
.br
Orient = integer()
.br
.RE
.RE
.RS
.LP
This constructor uses an already existing static box\&.
.RE
.LP
.nf

.B
new(Orient, Parent, Options :: [Option]) -> wxStaticBoxSizer()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
Orient = integer()
.br
Parent = wxWindow:wxWindow()
.br
Option = {label, unicode:chardata()}
.br
.RE
.RE
.RS
.LP
This constructor creates a new static box with the given label and parent window\&.
.RE
.LP
.nf

.B
getStaticBox(This) -> wxStaticBox:wxStaticBox()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxStaticBoxSizer()
.br
.RE
.RE
.RS
.LP
Returns the static box associated with the sizer\&.
.RE
.LP
.nf

.B
destroy(This :: wxStaticBoxSizer()) -> ok
.br
.fi
.br
.RS
.LP
Destroys the object\&.
.RE