.TH wxWebViewEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxWebViewEvent \- Functions for wxWebViewEvent class
.SH DESCRIPTION
.LP
A navigation event holds information about events associated with \fIwxWebView\fR\& objects\&.
.LP
Since: 2\&.9\&.3
.LP
See: \fIwxWebView\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxNotifyEvent\fR\& \fIwxCommandEvent\fR\& \fIwxEvent\fR\&
.LP
wxWidgets docs: wxWebViewEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxWebViewEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxWebViewEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxWebView()\fR\& = 
.br
    #wxWebView{type = wxWebViewEvent:wxWebViewEventType(),
.br
               string = unicode:chardata(),
.br
               int = integer(),
.br
               target = unicode:chardata(),
.br
               url = unicode:chardata()}
.br
.fi
.nf

\fBwxWebViewEventType()\fR\& = 
.br
    webview_navigating | webview_navigated | webview_loaded |
.br
    webview_error | webview_newwindow | webview_title_changed
.br
.fi
.SH EXPORTS
.LP
.nf

.B
getString(This) -> unicode:charlist()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxWebViewEvent()
.br
.RE
.RE
.RS
.LP
Returns item string for a listbox or choice selection event\&.
.LP
If one or several items have been deselected, returns the index of the first deselected item\&. If some items have been selected and others deselected at the same time, it will return the index of the first selected item\&.
.RE
.LP
.nf

.B
getInt(This) -> integer()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxWebViewEvent()
.br
.RE
.RE
.RS
.LP
Returns the integer identifier corresponding to a listbox, choice or radiobox selection (only if the event was a selection, not a deselection), or a boolean value representing the value of a checkbox\&.
.LP
For a menu item, this method returns -1 if the item is not checkable or a boolean value (true or false) for checkable items indicating the new state of the item\&.
.RE
.LP
.nf

.B
getTarget(This) -> unicode:charlist()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxWebViewEvent()
.br
.RE
.RE
.RS
.LP
Get the name of the target frame which the url of this event has been or will be loaded into\&.
.LP
This may return an empty string if the frame is not available\&.
.RE
.LP
.nf

.B
getURL(This) -> unicode:charlist()
.br
.fi
.br
.RS
.LP
Types:

.RS 3
This = wxWebViewEvent()
.br
.RE
.RE
.RS
.LP
Get the URL being visited\&.
.RE