.TH wxWindowCreateEvent 3 "wx 2.2.2" "wxWidgets team." "Erlang Module Definition"
.SH NAME
wxWindowCreateEvent \- Functions for wxWindowCreateEvent class
.SH DESCRIPTION
.LP
This event is sent just after the actual window associated with a \fIwxWindow\fR\& object has been created\&.
.LP
Since it is derived from \fIwxCommandEvent\fR\&, the event propagates up the window hierarchy\&.
.LP
See: Overview events, \fIwxWindowDestroyEvent\fR\& 
.LP
This class is derived (and can use functions) from: \fIwxCommandEvent\fR\& \fIwxEvent\fR\&
.LP
wxWidgets docs: wxWindowCreateEvent
.SH "EVENTS"

.LP
Use \fIwxEvtHandler:connect/3\fR\& with \fIwxWindowCreateEventType\fR\& to subscribe to events of this type\&.
.SH DATA TYPES
.nf

\fBwxWindowCreateEvent()\fR\& = wx:wx_object()
.br
.fi
.nf

\fBwxWindowCreate()\fR\& = 
.br
    #wxWindowCreate{type =
.br
                        wxWindowCreateEvent:wxWindowCreateEventType()}
.br
.fi
.nf

\fBwxWindowCreateEventType()\fR\& = create
.br
.fi